server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: usuario-service
          uri: http://localhost:8081
          predicates:
            - Path=/usuarios/**

        - id: categoria-service
          uri: http://localhost:8082
          predicates:
            - Path=/categorias/**

        - id: meme-service
          uri: http://localhost:8083
          predicates:
            - Path=/memes/**
